### ISSUE TITLE
Gitlab returning 409 error when creating merge request

### ISSUE THREAD

**Issue by martin-hewitt** [surevine/federated-scm#10]
````
2015-01-23 16:41:12 DEBUG GitlabCreateMergeRequestCommand:60 - REST POST call to http://gitlab/api/v3/projects/23/merge_requests
2015-01-23 16:41:12 DEBUG GitlabCreateMergeRequestCommand:61 - {target_project_id=[xx], target_branch=[master], id=[xx], title=[Automated Gateway merge request], source_branch=[master]}
2015-01-23 16:41:12 ERROR BundleProcessor:126 - Could not import new repository RepoBean{}
javax.ws.rs.ClientErrorException: HTTP 409 Conflict
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:196)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:154)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:444)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocationBuilder.post(ClientInvocationBuilder.java:201)
	at com.surevine.gateway.scm.scmclient.gitlab.GitlabCreateMergeRequestCommand.createMergeRequest(GitlabCreateMergeRequestCommand.java:65)
	at com.surevine.gateway.scm.scmclient.SCMCommand.createMergeRequest(SCMCommand.java:147)
	at com.surevine.gateway.scm.git.bundles.BundleProcessor.processBundle(BundleProcessor.java:123)
	at com.surevine.gateway.scm.IncomingProcessorImpl.processIncomingRepository(IncomingProcessorImpl.java:134)
	at com.surevine.gateway.scm.service.RestFederatorService.incomingBundle(RestFederatorService.java:139)
	at com.surevine.gateway.scm.service.RestFederatorService$Proxy$_$$_WeldClientProxy.incomingBundle(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:137)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:280)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:234)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:221)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:356)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:179)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:220)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:61)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:25)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:113)
	at io.undertow.security.handlers.AuthenticationCallHandler.handleRequest(AuthenticationCallHandler.java:52)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:45)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:61)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:70)
	at io.undertow.security.handlers.SecurityInitialHandler.handleRequest(SecurityInitialHandler.java:76)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:25)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:25)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:25)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:240)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:227)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:73)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:146)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:168)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:687)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
````

**Comment by martin-hewitt** [comment]
Pretty sure this is just as it says - there's a merge request open that's the same, so there's a conflict. This happens when the same bundle is applied repeatedly to the same two repositories. If the original MR is closed without merging, and the bundle imported again, the MR is created without this error.

In short, this is expected. I have updated the code to catch the exception and log it out rather than taking the whole process down with it.
